version: 2

sources:
  - name: gz_raw_data
    description: raw data
    loader: bigquery
    schema: gz_raw_data 
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez / we have on row per product_id found in each orders_id
        loaded_at_field: date_date
        columns:
        - name: date_date
          description: date of purchase
        - name: orders_id
          description: id de la orden
        - name: product_id
          description: identity of product
        - name: revenue
          description: amount of the sales
        - name: quantity
          description: how many of this product
        
      - name: product 
        identifier: raw_gz_product
        columns:
        - name: products_id
          tests: 
            - unique 
            - not_null
      - name: ship
        identifier: raw_gz_ship
        config:
          loaded_at_field: orders_id
        columns:
        - name: orders_id
          tests:
            - unique
            - not_null
         
