version: 2

sources:
  - name: gz_raw_data
    description: raw data
    loader: bigquery
    schema: gz_raw_data 
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez / we have on row per product_id found in each orders_id
        loaded_at_field: date_date
        columns:
        - name: date_date
          description: date of purchase
        - name: orders_id
          description: id de la orden
        - name: products_id
          description: identity of product
        - name: revenue
          description: amount of the sales
        - name: quantity
          description: how many of this product
        
      - name: product 
        identifier: raw_gz_product 
        description: products of Greenweez / we have one row per products_id and its purchase_price
        columns:
        - name: products_id
          description: identity of the product
        - name: purchSE_PRICE
          description: the price of each product

      - name: ship
        identifier: raw_gz_ship
        description: ship of Greenweez / we have one row per order_id and its shipping costs, fees & log costs assiociated
        columns:
        - name: orders_id
          description: identity of the order
        - name: shipping_fee
          description: shipping fees of the orders_id
        - name: logcost
          description: logcosts of the orders_id
        - name: ship_cost
          description: ship_cost of the orders_id